### PR TITLE
Portfolio

### PR DESCRIPTION
**Pull request by Namanvohraa**

### CODE REVIEW

**Comment by Namanvohraa** [comment]
@sachin-duhan26 please review 
#78

**Comment by Namanvohraa** [comment]
@sachin-duhan26 pleasee review 
#79

**Comment by Namanvohraa** [comment]
@sachin-duhan26 please review 
#80

**Comment by Namanvohraa** [comment]
@sachin-duhan26 Please review 
#81

**Review by sachin-duhan26 — APPROVED** [review]

**Pull request merged**
